export const JOBS = [
  {
    slug: "prediction-market-coo-ceo",
    title: "Prediction Market COO/CEO",
    domain: "Markets",
    location: "Remote / Chicago",
    seniority: "Executive",
    summary: "Lead a compact team scaling an industry prediction market. Domain depth in prediction markets, crypto exchanges, or adjacent marketplaces.",
    problem: "Take a live prediction market from compact product to durable exchange: strategy, GTM, risk, liquidity, and the team that can hold it.",
    outcomes: ["Set and execute strategy, roadmap, and GTM for market and exchange products.", "Build cross-functional teams across product, engineering, trading, ops, compliance.", "Own investor relationships, financial planning, and KPI reporting.", "Stand up risk, settlement, custody, and regulatory operating processes."],
    must: ["Direct experience at a prediction market, crypto exchange, betting or market-making business", "Scaled early-stage or high-growth marketplace / financial products", "P&L, fundraising, or investor-relations ownership", "Can work with engineering and trading without translation layer"],
    nice: ["Public company representation", "Regulatory markets background"],
    keywords: ["prediction market", "exchange", "crypto", "market making", "liquidity", "fundraising", "p&l", "coo", "ceo", "gtm", "compliance", "settlement"],
  },
  {
    slug: "lead-ai-legal-tech",
    title: "Lead AI Developer & Consultant (Legal Tech)",
    domain: "AI",
    location: "Remote / Chicago",
    seniority: "Lead",
    summary: "Bridge generative AI and legal services. Hands-on RAG, fine-tunes, agentic workflows, and enterprise security.",
    problem: "Legal firms need production LLM systems that survive privilege, audit, and identity constraints—not demos.",
    outcomes: ["Architect RAG pipelines, fine-tunes, and agentic workflows for legal work product.", "Lead an enterprise engineering team while remaining in the architecture.", "Ship SSO, RBAC, IAM, and production reliability."],
    must: ["LLM fine-tuning and agentic workflows in production", "RAG: parsing, embeddings, retrieval evaluation", "Python at a high level", "Enterprise team leadership, GitHub/Jira, CI/CD", "SSO / RBAC / IAM", "Azure or AWS administration"],
    nice: ["Legal domain experience", "On-prem / VPC deployments"],
    keywords: ["llm", "rag", "embeddings", "fine-tun", "agent", "python", "azure", "aws", "sso", "rbac", "iam", "legal", "ci/cd"],
  },
  {
    slug: "prediction-market-developer",
    title: "Prediction Market Developer",
    domain: "Markets",
    location: "Remote / Chicago",
    seniority: "Senior",
    summary: "Matching, market mechanics, pricing, onchain settlement, exchange and DeFi integrations.",
    problem: "The market is only as good as matching, resolution, and settlement. Build the parts that cannot be faked.",
    outcomes: ["Own services for routing, matching, settlement, and clearing.", "Iterate order types, AMM/PMM logic, resolution, fees.", "Integrate wallets, custody, and onchain settlement.", "Backtest market designs; keep production observable."],
    must: ["Built systems for prediction markets, crypto exchanges, or trading marketplaces", "Python, TypeScript/Node, or Go", "Order matching, AMMs, or marketplace mechanics", "Blockchain / wallet / custodian integrations", "Secure API design"],
    nice: ["DeFi primitives", "Market-risk tooling"],
    keywords: ["matching", "amm", "order book", "settlement", "onchain", "solidity", "python", "typescript", "go", "exchange", "prediction", "wallet"],
  },
  {
    slug: "ai-developer",
    title: "AI Developer",
    domain: "AI",
    location: "Remote / Chicago",
    seniority: "Mid–Senior",
    summary: "Ship MVPs with models in the loop. Use AI tools daily. Move prototypes into product components.",
    problem: "PCM ships across many bets. Need builders who treat models as material, not ceremony.",
    outcomes: ["Build MVPs for product features, tooling, and automation.", "Design, evaluate, and iterate LLM and model features.", "Advise other teams on model choice and failure modes."],
    must: ["Python and/or TypeScript", "Daily use of AI coding tools", "Model design or evaluation experience", "Can deliver useful MVPs and juggle parallel work"],
    nice: ["AWS/GCP/Azure", "embeddings / inference endpoints", "internal tools"],
    keywords: ["python", "typescript", "llm", "mvp", "openai", "langchain", "eval", "prompt", "automation"],
  },
  {
    slug: "software-developer",
    title: "Software Developer",
    domain: "Platform",
    location: "Remote / Chicago",
    seniority: "Mid–Senior",
    summary: "Production apps with AI as a first-class dependency. Python + TypeScript, APIs, inference endpoints.",
    problem: "Features have to land in real systems: auth, retries, tests, and something a user can press.",
    outcomes: ["Design application features that call models and services.", "Implement Python backends and TypeScript surfaces.", "Integrate third-party and inference APIs with real error paths."],
    must: ["Apps that use AI models or services", "Python and TypeScript", "REST/gRPC integrations", "Prompt / inference tradeoff literacy", "Tests, git, deployment basics"],
    nice: ["gRPC", "observability"],
    keywords: ["python", "typescript", "api", "react", "next", "inference", "ai", "rest", "grpc"],
  },
  {
    slug: "visual-software-engineer",
    title: "Visual Software Engineer",
    domain: "Machines",
    location: "Chicago preferred",
    seniority: "Senior",
    summary: "Pupil tracking, camera identification, robotics training, clear-LCD applications. Real-time visual systems.",
    problem: "Camera in, signal out, on time. Visual products fail in lighting, latency, and calibration—not in decks.",
    outcomes: ["Capture pipelines, real-time keypoints, calibration, monitoring.", "Display-driving code for clear LCD features.", "Label / train / eval / deploy loops.", "Profile CPU/GPU; ship diagnostics."],
    must: ["Python and/or C++ for near-real-time systems", "OpenCV / MediaPipe / PyTorch / TensorFlow", "Camera pipelines and sensor sync", "Display or graphics integration"],
    nice: ["Edge / ARM deploy", "LCD timing", "HCI for visual systems"],
    keywords: ["opencv", "computer vision", "mediapipe", "pytorch", "c++", "camera", "lcd", "realtime", "calibration", "gpu"],
  },
  {
    slug: "robotics-engineer",
    title: "Robotics Engineer",
    domain: "Machines",
    location: "West Loop, Chicago · 50% lab",
    seniority: "Senior",
    summary: "Software and firmware for specialized and humanoid robots. On-floor iteration in the Chicago RoboticsLab.",
    problem: "Robots that work on the floor, not in simulation theater. Control, perception, embedded, OTA.",
    outcomes: ["Control software, perception pipelines, embedded firmware.", "Sensor integration, state estimation, real-time loops.", "Firmware for motors, sensors, comms; HIL and on-floor tests.", "CI, diagnostics, deploy, OTA for lab devices."],
    must: ["Chicago-based or willing to relocate; 50%+ West Loop lab", "Python plus C/C++ or Rust", "Embedded / real-time systems", "Hardware-in-the-loop debugging"],
    nice: ["Humanoids", "ROS2", "motor control"],
    keywords: ["robotics", "firmware", "embedded", "ros", "c++", "rust", "control", "perception", "motor", "chicago", "humanoid"],
  },
];

export function getJob(slug) {
  return JOBS.find((j) => j.slug === slug);
}

export const DOMAINS = ["All", "Markets", "AI", "Machines", "Platform"];
